#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  2 18:59:06 2022

@author: henryandreumarquezsalinas
"""

import math


for i in range (100):

    if i>0 and i<=100 :
    
        i = i ^ (1/2) 
    
    elif i>100 and i<=300 :
    
        i = i-5

    else :
        
        i = 50
        
print(i)
    
